export enum ErrorType {
	INVALID_EMAIL = "INVALID_EMAIL",
	PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
	UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
	INVALID_PHONE = "INVALID_PHONE",
}

export enum InfoMessage {
	EMAIL_OTP_SENT = "EMAIL_OTP_SENT",
	PASSWORD_RESET_LINK_SENT = "PASSWORD_RESET_LINK_SENT",
	PHONE_OTP_SENT = "PHONE_OTP_SENT",
	PHONE_OTP_VERIFIED = "PHONE_OTP_VERIFIED",
	CONFIRMATION_EMAIL_SENT = "CONFIRMATION_EMAIL_SENT",
	EMAIL_OTP_VERIFIED = "EMAIL_OTP_VERIFIED",
}
