export enum ErrorType {
	INVALID_EMAIL = "INVALID_EMAIL",
	UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
}

export enum InfoMessage {
	MAGIC_LINK_SENT = "MAGIC_LINK_SENT",
}
